# Generated by Django 6.0 on 2026-03-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useraccount',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('pnumber', models.IntegerField(max_length=10)),
                ('role', models.CharField(choices=[('employer', 'Employer'), ('jobseeker', 'Jobseeker')], max_length=10)),
            ],
        ),
    ]
