# Generated by Django 6.0 on 2026-03-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='pnumber',
            field=models.IntegerField(),
        ),
    ]
