# Generated by Django 6.0 on 2026-03-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_useraccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='fname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='lname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='pnumber',
            field=models.CharField(max_length=15),
        ),
    ]
