# Generated by Django 6.0 on 2026-02-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employerdetails',
            fields=[
                ('empid', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=120)),
                ('emplocation', models.CharField(max_length=120)),
                ('empphone', models.CharField(max_length=120)),
                ('empemail', models.CharField(max_length=120)),
            ],
        ),
    ]
